version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.template:/etc/nginx/templates/default.conf.template
      - ../:/var/www
    ports:
      - 8088:80
    environment:
        - NGINX_PORT=80
    links:
      - php
    volumes_from:
      - app-data

  php:
    build: ./docker/php/
    expose:
      - 9000
    links:
      - mysql
    volumes_from:
      - app-data

  app-data:
    image: php:7.4-fpm
    volumes:
      - ./crm/:/var/www/html/crm
      - ./docker/index.html/:/var/www/html/index.html
    command: "true"

  mysql:
    image: mariadb:10.1.45
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    volumes_from:
      - mysql-data
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: i3crm
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
# docker exec -it seltzer_mysql_1 mysql -psecret -e "DROP DATABASE mydb; CREATE DATABASE mydb"

  mysql-data:
    image: mariadb:10.1.45
    volumes:
      - /var/lib/mysql
    command: "true"
